#!/usr/bin/env bash
# Stand up Golden Path in an isolated GCP sandbox project.
# Reads config/enterprise.env — never deploys into PARENT_PROJECT_ID.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
BOOTSTRAP_DIR="${REPO_ROOT}/platform/bootstrap"
# shellcheck source=../lib/load-config.sh
source "${REPO_ROOT}/scripts/lib/load-config.sh"

usage() {
  cat <<'EOF'
Usage: standup-teardown-env.sh [options]

Creates (if needed) an isolated Golden Path GCP project, links billing, and
runs platform/bootstrap terraform apply.

Requires: config/enterprise.env (copy from config/enterprise.env.example)

Options:
  --project-id <id>     GCP project ID (overrides GCP_SANDBOX_PROJECT)
  --project-name <name> Human-readable project name (default: from config)
  --github-org <org>    GitHub org for bootstrap tfvars (default: from config)
  --region <region>     GCP region (default: from config)
  --skip-apply          Create/link project only; do not run terraform apply
  --skip-labels         Skip gcloud alpha project labels (avoids hangs)
  --yes                 Skip confirmation before terraform apply
  -h, --help            Show help

Examples:
  cp config/enterprise.env.example config/enterprise.env
  ./scripts/standup-teardown-env.sh
  ./scripts/standup-teardown-env.sh --project-id my-org-gp-sandbox --yes
EOF
}

log() { printf '==> %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

SKIP_APPLY="false"
SKIP_LABELS="false"
ASSUME_YES="false"
OVERRIDE_PROJECT_ID=""
OVERRIDE_PROJECT_NAME=""
OVERRIDE_GITHUB_ORG=""
OVERRIDE_REGION=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-id) OVERRIDE_PROJECT_ID="$2"; shift 2 ;;
    --project-name) OVERRIDE_PROJECT_NAME="$2"; shift 2 ;;
    --github-org) OVERRIDE_GITHUB_ORG="$2"; shift 2 ;;
    --region) OVERRIDE_REGION="$2"; shift 2 ;;
    --skip-apply) SKIP_APPLY="true"; shift ;;
    --skip-labels) SKIP_LABELS="true"; shift ;;
    --yes) ASSUME_YES="true"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1" ;;
  esac
done

load_goldenpath_config "${REPO_ROOT}"

TEST_PROJECT_ID="${OVERRIDE_PROJECT_ID:-${GCP_SANDBOX_PROJECT}}"
TEST_PROJECT_NAME="${OVERRIDE_PROJECT_NAME:-${SANDBOX_PROJECT_NAME}}"
GITHUB_ORG="${OVERRIDE_GITHUB_ORG:-${GITHUB_ORG}}"
GCP_REGION="${OVERRIDE_REGION:-${GCP_REGION}}"
TEST_PROJECT_LABELS="${SANDBOX_PROJECT_LABELS:-}"

[[ -n "${TEST_PROJECT_ID}" ]] || die "set GCP_SANDBOX_PROJECT in config/enterprise.env or pass --project-id"

if [[ "${TEST_PROJECT_ID}" == "${PARENT_PROJECT_ID}" ]]; then
  die "sandbox project must differ from PARENT_PROJECT_ID (${PARENT_PROJECT_ID})"
fi

if goldenpath_is_protected_project "${TEST_PROJECT_ID}"; then
  die "refusing to use protected project as sandbox: ${TEST_PROJECT_ID}"
fi

if gcloud projects describe "${TEST_PROJECT_ID}" >/dev/null 2>&1; then
  log "project already exists: ${TEST_PROJECT_ID}"
else
  log "creating isolated project: ${TEST_PROJECT_ID}"
  gcloud projects create "${TEST_PROJECT_ID}" --name="${TEST_PROJECT_NAME}"
fi

if [[ "${SKIP_LABELS}" != "true" && -n "${TEST_PROJECT_LABELS}" ]]; then
  log "labeling project (best-effort, 30s max): ${TEST_PROJECT_LABELS}"
  if command -v timeout >/dev/null 2>&1; then
    timeout 30 gcloud alpha projects update "${TEST_PROJECT_ID}" \
      --update-labels="${TEST_PROJECT_LABELS}" 2>/dev/null \
      || log "skipped labels (timeout or gcloud alpha unavailable)"
  elif command -v gtimeout >/dev/null 2>&1; then
    gtimeout 30 gcloud alpha projects update "${TEST_PROJECT_ID}" \
      --update-labels="${TEST_PROJECT_LABELS}" 2>/dev/null \
      || log "skipped labels (timeout or gcloud alpha unavailable)"
  else
    log "skipped labels (pass --skip-labels or install coreutils timeout)"
  fi
fi

BILLING_LINKED="$(gcloud billing projects describe "${TEST_PROJECT_ID}" --format='value(billingEnabled)' 2>/dev/null || true)"
if [[ "${BILLING_LINKED}" == "True" ]]; then
  log "billing already linked for ${TEST_PROJECT_ID}"
else
  log "linking billing account ${BILLING_ACCOUNT_ID} (anchor: ${PARENT_PROJECT_ID})"
  gcloud billing projects link "${TEST_PROJECT_ID}" \
    --billing-account="billingAccounts/${BILLING_ACCOUNT_ID}"
fi

write_bootstrap_tfvars() {
  local ar_repo="${ARTIFACT_REGISTRY_REPO:-}"
  [[ -n "${ar_repo}" ]] || die "set ARTIFACT_REGISTRY_REPO in config/enterprise.env"
  cat > "${BOOTSTRAP_DIR}/terraform.tfvars" <<EOF
# Generated by standup-teardown-env.sh — personal_test sandbox
personal_test        = true
test_project_id      = "${TEST_PROJECT_ID}"
region               = "${GCP_REGION}"
github_org           = "${GITHUB_ORG}"
github_repo          = "${PLATFORM_REPO}"
artifact_registry_id = "${ar_repo}"
EOF
}

log "writing platform/bootstrap/terraform.tfvars for ${TEST_PROJECT_ID}"
write_bootstrap_tfvars

log "setting gcloud default project to ${TEST_PROJECT_ID} (isolated sandbox only)"
gcloud config set project "${TEST_PROJECT_ID}" >/dev/null

if [[ "${SKIP_APPLY}" == "true" ]]; then
  log "skip-apply set — project ready; run: cd platform/bootstrap && terraform apply"
  exit 0
fi

if [[ "${ASSUME_YES}" != "true" ]]; then
  echo ""
  echo "About to terraform apply Golden Path bootstrap in: ${TEST_PROJECT_ID}"
  echo "Parent project ${PARENT_PROJECT_ID} will NOT be modified."
  read -r -p "Continue? [y/N] " ans
  [[ "${ans}" =~ ^[Yy]$ ]] || exit 0
fi

log "terraform init + apply in ${BOOTSTRAP_DIR}"
(cd "${BOOTSTRAP_DIR}" && terraform init -input=false && terraform apply -auto-approve)

log "bootstrap complete"
echo ""
echo "Isolated project:  ${TEST_PROJECT_ID}"
echo "Billing anchor:    ${PARENT_PROJECT_ID} (unchanged)"
echo "GitHub org:        ${GITHUB_ORG}"
echo ""
echo "Scaffold a smoke service:"
echo "  shop config init --github-org ${GITHUB_ORG} --gcp-dev ${TEST_PROJECT_ID}"
echo "  ./cli/shop new my-service --template nextjs --output .."
echo ""
echo "Teardown when done:"
echo "  ./scripts/teardown-personal-test.sh --delete-project ${TEST_PROJECT_ID} --yes"