#!/usr/bin/env python3
"""Golden Path — data-store injection for scaffolded services.

Given a base scaffold (already copied + token-replaced) and a validated
:class:`service_composer.ServiceConfig`, layer on everything needed to attach
the selected data store(s):

  * modular Terraform (``infra/data-stores.tf``) composing the store module(s)
    and wiring their outputs into the existing ``cloud_run`` module block;
  * per-store variables (with defaults from the chosen config) + tfvars values;
  * a language-matched connection layer (Python/Node) with a startup health
    check, kept separate from business logic;
  * runtime dependencies; and a README section documenting the wiring.

This release implements **Cloud SQL (PostgreSQL)** attaching to server-mode
templates. All values are resolved at write time — no ``{{TOKEN}}`` is emitted,
so ``validate_no_tokens_remain`` (scripts/lib/scaffold-tokens.sh) stays green.
"""

from __future__ import annotations

from pathlib import Path

import service_composer as sc

# Template → connection-layer language.
_TEMPLATE_LANGUAGE = {
    "fastapi": "python",
    "streamlit": "python",
    "express": "node",
    "nextjs": "node",
    "react-spa": "node",
    "svelte-spa": "node",
}

# Templates whose health endpoint we auto-wire with a DB ping this release.
_HEALTH_WIRED = {"fastapi", "express"}

_FRAGMENTS_DIR = Path(__file__).resolve().parent.parent.parent / "templates" / "_fragments"


def _module_source(github_org: str, platform_repo: str, version: str, module: str) -> str:
    return (
        f"git::https://github.com/{github_org}/{platform_repo}.git"
        f"//modules/{module}?ref={version}"
    )


def language_for(template: str, runtime: str) -> str:
    return _TEMPLATE_LANGUAGE.get(template, "python" if runtime == "python" else "node")


def apply_data_stores(
    service_dir: Path,
    service_config: sc.ServiceConfig,
    *,
    github_org: str,
    platform_repo: str,
    goldenpath_version: str,
) -> list[str]:
    """Inject data-store wiring into a scaffolded service.

    Returns a list of human-readable notes about what was generated.
    Only Cloud SQL is implemented; other (disabled) stores are skipped.
    """
    notes: list[str] = []
    cloud_sql = next(
        (s for s in service_config.data_stores if s.id == "cloud_sql"), None
    )
    if cloud_sql is None:
        return notes

    language = language_for(service_config.template, service_config.runtime)
    conf = cloud_sql.config
    ip_mode = conf.get("ip_mode", "public")
    is_private = ip_mode == "private"

    _write_data_stores_tf(
        service_dir,
        conf,
        is_private=is_private,
        github_org=github_org,
        platform_repo=platform_repo,
        version=goldenpath_version,
    )
    notes.append("infra/data-stores.tf (Cloud SQL PostgreSQL module)")

    _append_variables(service_dir, conf, is_private=is_private)
    _append_tfvars(service_dir, conf, service_config.environments, is_private=is_private)
    _wire_cloud_run_env(service_dir, ip_mode=ip_mode, is_private=is_private)

    notes.extend(_write_connection_layer(service_dir, service_config.template, language))
    _write_readme_section(service_dir, service_config, ip_mode=ip_mode, language=language)
    notes.append("README: Cloud SQL connection & deploy notes")

    return notes


# ── Terraform ─────────────────────────────────────────────────────────────────


def _write_data_stores_tf(
    service_dir: Path,
    conf: dict,
    *,
    is_private: bool,
    github_org: str,
    platform_repo: str,
    version: str,
) -> None:
    cloud_sql_src = _module_source(github_org, platform_repo, version, "cloud-sql")
    vpc_src = _module_source(github_org, platform_repo, version, "vpc-connector")

    blocks = [
        "# ── Data stores (generated by Golden Path) ──────────────────────────────────",
        "",
        'module "cloud_sql" {',
        f'  source = "{cloud_sql_src}"',
        "",
        "  project_id   = var.project_id",
        "  region       = var.region",
        "  service_name = var.service_name",
        "  environment  = var.environment",
        "",
        "  runtime_service_account_email  = module.identity.email",
        "  runtime_service_account_member = module.identity.member",
        "",
        "  database_version    = var.db_version",
        "  tier                = var.db_tier",
        "  high_availability   = var.db_high_availability",
        "  ip_mode             = var.db_ip_mode",
        "  database_name       = var.db_name",
        "  deletion_protection = var.db_deletion_protection",
    ]
    if is_private:
        blocks.append("  network             = var.db_network")
    blocks.append("}")

    if is_private:
        blocks += [
            "",
            'module "vpc_connector" {',
            f'  source = "{vpc_src}"',
            "",
            "  project_id   = var.project_id",
            "  region       = var.region",
            "  service_name = var.service_name",
            "  environment  = var.environment",
            "  network      = var.db_network",
            "}",
        ]

    (service_dir / "infra" / "data-stores.tf").write_text(
        "\n".join(blocks) + "\n", encoding="utf-8"
    )


def _append_variables(service_dir: Path, conf: dict, *, is_private: bool) -> None:
    version = conf.get("version", "POSTGRES_16")
    tier = conf.get("tier", "db-f1-micro")
    ha = "true" if conf.get("high_availability") else "false"
    ip_mode = conf.get("ip_mode", "public")
    db_name = conf.get("database_name", "appdb")
    deletion = "false" if conf.get("deletion_protection") is False else "true"

    lines = [
        "",
        "# ── Cloud SQL (generated) ─────────────────────────────────────────────────────",
        'variable "db_version" {',
        "  type    = string",
        f'  default = "{version}"',
        "}",
        "",
        'variable "db_tier" {',
        "  type    = string",
        f'  default = "{tier}"',
        "}",
        "",
        'variable "db_high_availability" {',
        "  type    = bool",
        f"  default = {ha}",
        "}",
        "",
        'variable "db_ip_mode" {',
        "  type    = string",
        f'  default = "{ip_mode}"',
        "}",
        "",
        'variable "db_name" {',
        "  type    = string",
        f'  default = "{db_name}"',
        "}",
        "",
        'variable "db_deletion_protection" {',
        "  type    = bool",
        f"  default = {deletion}",
        "}",
    ]
    if is_private:
        network = conf.get("network", "")
        lines += [
            "",
            'variable "db_network" {',
            "  type    = string",
            f'  default = "{network}"',
            "}",
        ]

    path = service_dir / "infra" / "variables.tf"
    path.write_text(path.read_text(encoding="utf-8") + "\n".join(lines) + "\n", encoding="utf-8")


def _append_tfvars(
    service_dir: Path, conf: dict, environments: list[str], *, is_private: bool
) -> None:
    version = conf.get("version", "POSTGRES_16")
    tier = conf.get("tier", "db-f1-micro")
    ha = "true" if conf.get("high_availability") else "false"
    ip_mode = conf.get("ip_mode", "public")
    db_name = conf.get("database_name", "appdb")
    deletion = "false" if conf.get("deletion_protection") is False else "true"

    lines = [
        "",
        "# Cloud SQL (generated)",
        f'db_version             = "{version}"',
        f'db_tier                = "{tier}"',
        f"db_high_availability   = {ha}",
        f'db_ip_mode             = "{ip_mode}"',
        f'db_name                = "{db_name}"',
        f"db_deletion_protection = {deletion}",
    ]
    if is_private:
        lines.append(f'db_network             = "{conf.get("network", "")}"')

    for env in environments:
        tfvars = service_dir / "infra" / f"{env}.tfvars"
        if tfvars.exists():
            tfvars.write_text(
                tfvars.read_text(encoding="utf-8") + "\n".join(lines) + "\n",
                encoding="utf-8",
            )


def _wire_cloud_run_env(service_dir: Path, *, ip_mode: str, is_private: bool) -> None:
    """Inject DB env vars (and VPC connector) into the cloud_run module block."""
    main_tf = service_dir / "infra" / "main.tf"
    text = main_tf.read_text(encoding="utf-8")

    env_anchor = "    SERVICE_NAME = var.service_name\n    ENVIRONMENT  = var.environment\n"
    if env_anchor in text:
        db_env = (
            env_anchor
            + "    INSTANCE_CONNECTION_NAME = module.cloud_sql.instance_connection_name\n"
            + "    DB_NAME                  = module.cloud_sql.database\n"
            + "    DB_IAM_USER              = module.cloud_sql.iam_user\n"
            + f'    DB_IP_TYPE               = "{ip_mode}"\n'
        )
        text = text.replace(env_anchor, db_env, 1)

    if is_private:
        # Add vpc_connector to the cloud_run module inputs (before its env map).
        cr_env_open = "\n  env = {"
        if "vpc_connector" not in text and cr_env_open in text:
            text = text.replace(
                cr_env_open,
                "\n  vpc_connector = module.vpc_connector.id\n" + cr_env_open,
                1,
            )

    main_tf.write_text(text, encoding="utf-8")


# ── Connection layer ──────────────────────────────────────────────────────────


def _write_connection_layer(service_dir: Path, template: str, language: str) -> list[str]:
    notes: list[str] = []
    if language == "python":
        src = _FRAGMENTS_DIR / "data-stores" / "cloud-sql" / "python" / "db.py"
        dest = service_dir / "app" / "db.py"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
        notes.append("app/db.py (Cloud SQL Python connector + SQLAlchemy)")
        _add_python_deps(service_dir)
        if template in _HEALTH_WIRED:
            _wire_fastapi_health(service_dir)
            notes.append("app/main.py: /api/db-health endpoint")
    else:
        src = _FRAGMENTS_DIR / "data-stores" / "cloud-sql" / "node" / "db.js"
        dest = service_dir / "src" / "db.js"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
        notes.append("src/db.js (Cloud SQL Node connector + pg)")
        _add_node_deps(service_dir)
        if template in _HEALTH_WIRED:
            _wire_express_health(service_dir)
            notes.append("src/index.js: /api/db-health route")
    return notes


def _add_python_deps(service_dir: Path) -> None:
    req = service_dir / "requirements.txt"
    deps = ["cloud-sql-python-connector[pg8000]>=1.9.0", "SQLAlchemy>=2.0.0"]
    existing = req.read_text(encoding="utf-8") if req.exists() else ""
    additions = [d for d in deps if d.split(">=")[0].split("[")[0].lower() not in existing.lower()]
    if additions:
        sep = "" if existing.endswith("\n") or not existing else "\n"
        req.write_text(existing + sep + "\n".join(additions) + "\n", encoding="utf-8")


def _add_node_deps(service_dir: Path) -> None:
    import json

    pkg_path = service_dir / "package.json"
    if not pkg_path.exists():
        return
    pkg = json.loads(pkg_path.read_text(encoding="utf-8"))
    deps = pkg.setdefault("dependencies", {})
    deps.setdefault("@google-cloud/cloud-sql-connector", "^1.3.0")
    deps.setdefault("pg", "^8.12.0")
    pkg_path.write_text(json.dumps(pkg, indent=2) + "\n", encoding="utf-8")


def _wire_fastapi_health(service_dir: Path) -> None:
    main_py = service_dir / "app" / "main.py"
    if not main_py.exists():
        return
    text = main_py.read_text(encoding="utf-8")
    if "/api/db-health" in text:
        return
    addition = (
        "\n\n"
        "from app.db import check_connection  # noqa: E402\n\n\n"
        '@app.get("/api/db-health")\n'
        "def db_health():\n"
        "    \"\"\"Verify the Cloud SQL connection (IAM auth).\"\"\"\n"
        "    check_connection()\n"
        '    return {"status": "ok", "database": "reachable"}\n'
    )
    main_py.write_text(text.rstrip() + addition, encoding="utf-8")


def _wire_express_health(service_dir: Path) -> None:
    index_js = service_dir / "src" / "index.js"
    if not index_js.exists():
        return
    text = index_js.read_text(encoding="utf-8")
    if "/api/db-health" in text:
        return
    # Add the import after the express import.
    if 'import { checkConnection }' not in text:
        text = text.replace(
            'import express from "express";',
            'import express from "express";\nimport { checkConnection } from "./db.js";',
            1,
        )
    # Add the route before app.listen(...).
    route = (
        'app.get("/api/db-health", async (_req, res) => {\n'
        "  try {\n"
        "    await checkConnection();\n"
        '    res.json({ status: "ok", database: "reachable" });\n'
        "  } catch (err) {\n"
        '    res.status(503).json({ status: "error", detail: String(err) });\n'
        "  }\n"
        "});\n\n"
    )
    text = text.replace("app.listen(", route + "app.listen(", 1)
    index_js.write_text(text, encoding="utf-8")


# ── README ────────────────────────────────────────────────────────────────────


def _write_readme_section(
    service_dir: Path, cfg: sc.ServiceConfig, *, ip_mode: str, language: str
) -> None:
    store = next(s for s in cfg.data_stores if s.id == "cloud_sql")
    conf = store.config
    health_path = "/api/db-health" if cfg.template in _HEALTH_WIRED else "(wire check_connection into your health route)"
    section = f"""

## Data store: Cloud SQL (PostgreSQL)

This service was generated with a Cloud SQL PostgreSQL instance attached, using
**IAM database authentication** (no password is created or stored).

**Chosen options**

| Option | Value |
|--------|-------|
| Engine | PostgreSQL ({conf.get("version", "POSTGRES_16")}) |
| Tier | {conf.get("tier", "db-f1-micro")} |
| High availability | {"yes (REGIONAL)" if conf.get("high_availability") else "no (ZONAL)"} |
| IP mode | {ip_mode} |
| Database | {conf.get("database_name", "appdb")} |

**Runtime environment variables** (set by Terraform on Cloud Run)

| Variable | Meaning |
|----------|---------|
| `INSTANCE_CONNECTION_NAME` | `project:region:instance` |
| `DB_NAME` | application database name |
| `DB_IAM_USER` | IAM DB user (the runtime service account) |
| `DB_IP_TYPE` | `{ip_mode}` |

**Connection layer**: `{"app/db.py" if language == "python" else "src/db.js"}`
(kept separate from business logic). Health check exposed at `{health_path}`.

**Deploy**

```bash
cd infra
terraform init \\
  -backend-config="bucket=YOUR_ORG-goldenpath-tfstate" \\
  -backend-config="prefix=services/{cfg.service_name}"
terraform apply -var-file=dev.tfvars   # single plan/apply provisions DB + service
```

The runtime service account is granted `roles/cloudsql.client` and
`roles/cloudsql.instanceUser` only. Required APIs are enabled by the module.
"""
    readme = service_dir / "README.md"
    existing = readme.read_text(encoding="utf-8") if readme.exists() else f"# {cfg.service_name}\n"
    readme.write_text(existing.rstrip() + section, encoding="utf-8")
