"""Cloud SQL (PostgreSQL) connection layer — IAM database authentication.

Generated by Golden Path. Kept separate from business logic. All configuration
comes from the environment (set by Terraform on the Cloud Run service):

    INSTANCE_CONNECTION_NAME   project:region:instance
    DB_NAME                    application database name
    DB_IAM_USER                IAM DB user (the runtime service account)
    DB_IP_TYPE                 "public" (default) or "private"

Auth uses the runtime service account's OAuth token via the Cloud SQL Python
Connector — there is no password to manage or store.
"""

from __future__ import annotations

import os
from functools import lru_cache

import sqlalchemy
from google.cloud.sql.connector import Connector, IPTypes


def _ip_type() -> IPTypes:
    return IPTypes.PRIVATE if os.getenv("DB_IP_TYPE", "public").lower() == "private" else IPTypes.PUBLIC


@lru_cache(maxsize=1)
def get_engine() -> sqlalchemy.engine.Engine:
    """Return a process-wide SQLAlchemy engine backed by the Cloud SQL connector."""
    connector = Connector(ip_type=_ip_type(), enable_iam_auth=True)

    def getconn():
        return connector.connect(
            os.environ["INSTANCE_CONNECTION_NAME"],
            "pg8000",
            user=os.environ["DB_IAM_USER"],
            db=os.environ["DB_NAME"],
            enable_iam_auth=True,
        )

    return sqlalchemy.create_engine(
        "postgresql+pg8000://",
        creator=getconn,
        pool_size=5,
        max_overflow=2,
        pool_pre_ping=True,
    )


def check_connection() -> bool:
    """Startup/health check — returns True if the database answers ``SELECT 1``."""
    with get_engine().connect() as conn:
        conn.execute(sqlalchemy.text("SELECT 1"))
    return True
