# Pure PowerShell GCP bootstrap — gcloud + terraform only (no bash scripts).
Set-StrictMode -Version Latest

function Get-EnterpriseEnv([string]$RepoRoot) {
    $profile = @{}
    $example = Join-Path $RepoRoot "config/enterprise.env.example"
    if (Test-Path $example) {
        Get-Content $example | ForEach-Object {
            if ($_ -match '^\s*([A-Z_]+)=(.*)$') {
                $profile[$Matches[1]] = $Matches[2].Trim().Trim('"')
            }
        }
    }
    $envFile = Join-Path $RepoRoot "config/enterprise.env"
    if (-not (Test-Path $envFile)) {
        throw "Missing $envFile — copy config/enterprise.env.example to config/enterprise.env"
    }
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^\s*([A-Z_]+)=(.*)$') {
            $profile[$Matches[1]] = $Matches[2].Trim().Trim('"')
        }
    }
    return $profile
}

function Get-GcpProjectDisplayName {
    param(
        [string]$DisplayName,
        [string]$ProjectId = "",
        [string]$Fallback = "Golden Path Sandbox"
    )
    $name = if ($DisplayName) { $DisplayName.Trim() }
            elseif ($ProjectId) { $ProjectId }
            else { $Fallback }
    if ($name.Length -le 30) { return $name }
    return $name.Substring(0, 30)
}

function Test-TerraformApiPropagationError([string]$Detail) {
    if ([string]::IsNullOrWhiteSpace($Detail)) { return $false }
    return $Detail -match 'workloadIdentityPools\.create|artifactregistry\.repositories\.create|IAM_PERMISSION_DENIED'
}

function Write-BootstrapTfvars {
    param([string]$BootstrapDir, [hashtable]$Config, [hashtable]$Profile)
    $arRepo = $Profile.ARTIFACT_REGISTRY_REPO
    if (-not $arRepo) { throw "set ARTIFACT_REGISTRY_REPO in config/enterprise.env" }
    $content = @"
# Generated by Golden Path PowerShell wizard
personal_test        = true
test_project_id      = "$($Config.gcp_project)"
region               = "$($Config.gcp_region)"
github_org           = "$($Config.github_org)"
github_repo          = "$($Config.github_platform_repo)"
artifact_registry_id = "$arRepo"
"@
    Set-Content -Path (Join-Path $BootstrapDir "terraform.tfvars") -Value $content -Encoding UTF8
}

function Invoke-GoldenPathBootstrap {
    param(
        [string]$RepoRoot,
        [hashtable]$Config,
        [scriptblock]$InvokeExternal
    )

    $profile = Get-EnterpriseEnv $RepoRoot
    $parent = $profile.PARENT_PROJECT_ID
    $billing = $profile.BILLING_ACCOUNT_ID
    $project = $Config.gcp_project
    $display = Get-GcpProjectDisplayName -DisplayName $Config.project_display_name -ProjectId $project
    $bootstrapDir = Join-Path $RepoRoot "platform/bootstrap"

    if ($project -eq $parent) { throw "Project must differ from parent billing project ($parent)" }

    $exists = & $InvokeExternal "gcloud" @("projects", "describe", $project)
    if ($exists.ExitCode -ne 0) {
        $create = & $InvokeExternal "gcloud" @("projects", "create", $project, "--name=$display")
        if ($create.ExitCode -ne 0) { throw "gcloud projects create failed: $($create.StdErr)" }
    }

    $billingState = & $InvokeExternal "gcloud" @("billing", "projects", "describe", $project, "--format=value(billingEnabled)")
    if ($billingState.StdOut.Trim() -ne "True") {
        $link = & $InvokeExternal "gcloud" @(
            "billing", "projects", "link", $project,
            "--billing-account=billingAccounts/$billing"
        )
        if ($link.ExitCode -ne 0) { throw "billing link failed: $($link.StdErr)" }
    }

    Write-BootstrapTfvars $bootstrapDir $Config $profile
    & $InvokeExternal "gcloud" @("config", "set", "project", $project) | Out-Null
    & $InvokeExternal "gcloud" @("auth", "application-default", "set-quota-project", $project) | Out-Null

    $init = & $InvokeExternal "terraform" @("init", "-input=false") -WorkDir $bootstrapDir
    if ($init.ExitCode -ne 0) {
        $detail = if ($init.StdErr) { $init.StdErr.Trim() } else { $init.StdOut.Trim() }
        throw "terraform init failed: $detail"
    }
    $apply = & $InvokeExternal "terraform" @("apply", "-auto-approve", "-input=false") -WorkDir $bootstrapDir
    if ($apply.ExitCode -ne 0) {
        $detail = if ($apply.StdErr) { $apply.StdErr.Trim() } else { $apply.StdOut.Trim() }
        if (Test-TerraformApiPropagationError $detail) {
            Write-Host "  GCP APIs may still be propagating — retrying terraform apply in 15s..." -ForegroundColor DarkGray
            Start-Sleep -Seconds 15
            $apply = & $InvokeExternal "terraform" @("apply", "-auto-approve", "-input=false") -WorkDir $bootstrapDir
            if ($apply.ExitCode -eq 0) { return $true }
            $detail = if ($apply.StdErr) { $apply.StdErr.Trim() } else { $apply.StdOut.Trim() }
        }
        throw "terraform apply failed: $detail"
    }

    return $true
}

function Invoke-GoldenPathTeardown {
    param(
        [string]$RepoRoot,
        [bool]$DeleteProject,
        [scriptblock]$InvokeExternal,
        [string]$ExpectedProjectId = "",
        [string[]]$ProtectedProjects = @()
    )

    $bootstrapDir = Join-Path $RepoRoot "platform/bootstrap"
    $tfvars = Join-Path $bootstrapDir "terraform.tfvars"
    if (-not (Test-Path $tfvars)) { throw "Missing $tfvars — run bootstrap first" }
    $content = Get-Content $tfvars -Raw
    if ($content -notmatch 'personal_test\s*=\s*true') {
        throw "terraform.tfvars must have personal_test = true (safety check)"
    }
    if ($content -notmatch 'test_project_id\s*=\s*"([^"]+)"') {
        throw "Could not parse test_project_id from terraform.tfvars"
    }
    $projectId = $Matches[1]

    if ($ExpectedProjectId -and $projectId -ne $ExpectedProjectId) {
        throw "terraform.tfvars targets '$projectId' but wizard config has '$ExpectedProjectId' — re-bootstrap (menu 3) or align menu 12 first"
    }

    $init = & $InvokeExternal "terraform" @("init", "-input=false") -WorkDir $bootstrapDir
    if ($init.ExitCode -ne 0) {
        $detail = if ($init.StdErr) { $init.StdErr.Trim() } else { $init.StdOut.Trim() }
        throw "terraform init failed: $detail"
    }

    $destroy = & $InvokeExternal "terraform" @("destroy", "-auto-approve", "-input=false") -WorkDir $bootstrapDir
    if ($destroy.ExitCode -ne 0) {
        $detail = if ($destroy.StdErr) { $destroy.StdErr.Trim() } else { $destroy.StdOut.Trim() }
        throw "terraform destroy failed: $detail"
    }

    if ($DeleteProject) {
        if ($ProtectedProjects -contains $projectId) {
            throw "Refusing to delete protected project '$projectId'"
        }
        $del = & $InvokeExternal "gcloud" @("projects", "delete", $projectId, "--quiet")
        if ($del.ExitCode -ne 0) { throw "gcloud projects delete failed: $($del.StdErr)" }
    }
    return $projectId
}